- name: Install Docker
  apt: pkg=docker.io state=present
  register: dockerinstalled

- name: Pull Image
  when: dockerinstalled|success
  docker_image:
   name: "{{ imagename }}"
  notify:
   - Start a container

- name: Start this shit
  docker_container:
   name: "{{ containername }}"
   image: "{{ imagename }}"
   state: started
   volumes:
    - "/bobo:/toto:rwm"
   ports:
    - "222:22"
    - "880:80"
   interactive: yes
   entrypoint: "/bin/bash" 
